theme: jekyll-theme-hacker
title: Taller de herramientas para *Big Data*
description: Material del taller
author: Juan Pabo Soto y Julio Waissman

show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

